
name: "Check API"

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  check-api:
    name: check-api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: check
        run: npm run check
