name: getting-started-cached-ui5
on:
  push:
    branches: [ "run-github-actions-cached-ui5-on-the-fly" ]
jobs:
  getting-started-cached-ui5:
    name: getting-started-cached-ui5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
        sap-ui5-version: [ 1.110.1, 1.113.0, 1.114.0 ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: tmp/sapui5/full-${{ matrix.sap-ui5-version }}/dist
          key: sapui5-full-${{ matrix.sap-ui5-version }}

      - name: Build UI5
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./test/bin/build.ui5.sh

      - uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: tmp/sapui5/${{ matrix.sap-ui5-version }}/dist
          key: sapui5-full-${{ matrix.sap-ui5-version }}

      - name: list cache
        run: ls -altr tmp/sapui5/${{ matrix.sap-ui5-version }}/dist

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: prepare
        run: npm i
  
      - name: selenium
        run: docker run -d -p 4444:4444 --network host selenium/standalone-chrome

      - name: test
        env:
          TOKEN: ${{ secrets.MY_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: SELENIUM_REMOTE_URL="http://127.0.0.1:4444/wd/hub" bash ./test/bin/testGettingStartedReuseUI5LocalBuild.sh
