name: "Getting started"

on:
  push:
    branches: [ "run-guthub-action-getting-started" ]

jobs:
  getting-started:
    name: getting-started
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: selenium
        run: |
          docker run -d -p 4444:4444 --network host selenium/standalone-chrome
      - name: Getting started
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          SELENIUM_REMOTE_URL="http://127.0.0.1:4444/wd/hub" bash ./test/bin/testGettingStarted683.sh
          SELENIUM_REMOTE_URL="http://127.0.0.1:4444/wd/hub" bash ./test/bin/testGettingStarted700.sh
